language: go

go:
 - 1.x
 - tip

matrix:
  fast_finish: true

env:
  global:
    - PATH=$HOME/gopath/bin:$PATH

install:
 - go get -t -v ./...
 - go  install -a -race std

script:
 - go tool vet -all .
 - go build ./...
 - go test -race -v ./...
