version: "{build}"

os: Windows Server 2012 R2

clone_folder: c:\projects\src\github.com\rjeczalik\ciexec

environment:
 GOPATH: c:\projects

install:
 - set PATH=%GOPATH%\bin;%PATH%
 - cd %APPVEYOR_BUILD_FOLDER%
 - go version
 - go get -v -t ./...
 - go  install -a -race std

build_script:
 - go tool vet -all .
 - go build ./...
 - go test -race -v ./...

test: off

deploy: off
